import 'package:acrostics_maker/data/dict_big.dart';

class Globals {
  static String DB_PREFIX = "";
  static bool isAppStarted = false;
  static String removeAdsProductId = "remove_ads";
  static String priceNoAds = "\$1";
  static bool isTesting = false;
  static bool isAds = true;
  static bool isForceAds = false; //BYPASSES IF ALREADY BOUGHT..
  static bool isWorkOffline = false;
  static bool isAppOnline = false;
  static dynamic defaultLanguage = {
    "LID": "8",
    "name1": "English",
    "name2": "LANGUAGE_ENGLISH",
    "value": "en",
  };

  static List<dynamic> languages = [
    {
      "LID": "1",
      "name1": "Afrikaans",
      "name2": "LANGUAGE_AFRIKAANS",
      "value": "af"
    },
    {"LID": "2", "name1": "Euskara", "name2": "LANGUAGE_BASQUE", "value": "eu"},
    {
      "LID": "3",
      "name1": "Bosanski",
      "name2": "LANGUAGE_BOSNIAN",
      "value": "bs"
    },
    {
      "LID": "4",
      "name1": "Hrvatski",
      "name2": "LANGUAGE_CROATIAN",
      "value": "hr"
    },
    {"LID": "5", "name1": "čeština", "name2": "LANGUAGE_CZECH", "value": "cs"},
    {"LID": "6", "name1": "Dansk", "name2": "LANGUAGE_DANISH", "value": "da"},
    {
      "LID": "8",
      "name1": "English",
      "name2": "LANGUAGE_ENGLISH",
      "value": "en"
    },
    {
      "LID": "9",
      "name1": "Eesti keel",
      "name2": "LANGUAGE_ESTONIAN",
      "value": "et"
    },
    {
      "LID": "11",
      "name1": "Suomalainen",
      "name2": "LANGUAGE_FINNISH",
      "value": "fi"
    },
    {
      "LID": "12",
      "name1": "Français",
      "name2": "LANGUAGE_FRENCH",
      "value": "fr"
    },
    {
      "LID": "13",
      "name1": "Deutsch",
      "name2": "LANGUAGE_GERMAN",
      "value": "de"
    },
    {
      "LID": "14",
      "name1": "Kreyòl ayisyen",
      "name2": "LANGUAGE_HAITIAN_CREOLE",
      "value": "ht"
    },
    {
      "LID": "15",
      "name1": "ʻŌlelo Hawaiʻi",
      "name2": "LANGUAGE_HAWAIIAN",
      "value": "haw"
    },
    {"LID": "16", "name1": "Hmoob", "name2": "LANGUAGE_HMONG", "value": "hmn"},
    {
      "LID": "17",
      "name1": "Magyar",
      "name2": "LANGUAGE_HUNGARIAN",
      "value": "hu"
    },
    {
      "LID": "18",
      "name1": "Bahasa Indonesia",
      "name2": "LANGUAGE_INDONESIAN",
      "value": "id"
    },
    {"LID": "19", "name1": "Gaeilge", "name2": "LANGUAGE_IRISH", "value": "ga"},
    {
      "LID": "20",
      "name1": "Italiano",
      "name2": "LANGUAGE_ITALIAN",
      "value": "it"
    },
    {
      "LID": "22",
      "name1": "Lëtzebuergesch",
      "name2": "LANGUAGE_LUXEMBOURGISH",
      "value": "lb"
    },
    {"LID": "23", "name1": "Melayu", "name2": "LANGUAGE_MALAY", "value": "ms"},
    {"LID": "24", "name1": "Malti", "name2": "LANGUAGE_MALTESE", "value": "mt"},
    {"LID": "25", "name1": "Maori", "name2": "LANGUAGE_MAORI", "value": "mi"},
    {"LID": "27", "name1": "Polski", "name2": "LANGUAGE_POLISH", "value": "pl"},
    {
      "LID": "28",
      "name1": "Português",
      "name2": "LANGUAGE_PORTUGUESE",
      "value": "pt"
    },
    {
      "LID": "29",
      "name1": "Română",
      "name2": "LANGUAGE_ROMANIAN",
      "value": "ro"
    },
    {"LID": "30", "name1": "Samoa", "name2": "LANGUAGE_SAMOAN", "value": "sm"},
    {
      "LID": "31",
      "name1": "Slovensko",
      "name2": "LANGUAGE_SLOVAK",
      "value": "sk"
    },
    {
      "LID": "32",
      "name1": "Slovenščina",
      "name2": "LANGUAGE_SLOVENIAN",
      "value": "sl"
    },
    {
      "LID": "33",
      "name1": "Soomaali",
      "name2": "LANGUAGE_SOMALI",
      "value": "so"
    },
    {
      "LID": "34",
      "name1": "Español",
      "name2": "LANGUAGE_SPANISH",
      "value": "es"
    },
    {
      "LID": "35",
      "name1": "Svenska",
      "name2": "LANGUAGE_SWEDISH",
      "value": "sv"
    },
    {"LID": "39", "name1": "Cymraeg", "name2": "LANGUAGE_WELSH", "value": "cy"}
  ];
  static List<dynamic> availLanguages = [Globals.defaultLanguage];
  static dynamic appLanguage = Globals.defaultLanguage;
  static dynamic selectedAcrosticsLanguage = Globals.languages
      .firstWhere((lang) => lang["LID"] == Globals.defaultLanguage["LID"]);
  static Map<String, List<Map<String, String>>> myDic = {
    "A": [dicA1, dicA2],
    "B": [dicB1, dicB2],
    "C": [dicC1, dicC1, dicC3],
    "D": [dicD1, dicD2],
    "E": [dicE1],
    "F": [dicF1],
    "G": [dicG1],
    "H": [dicH1],
    "I": [dicI1],
    "J": [dicJ1],
    "K": [dicK1],
    "L": [dicL1],
    "M": [dicM1, dicM2],
    "N": [dicN1],
    "O": [dicO1],
    "P": [dicP1, dicP2],
    "Q": [dicQ1],
    "R": [dicR1, dicR2],
    "S": [dicS1, dicS2, dicS3],
    "T": [dicT1, dicT2],
    "U": [dicU1],
    "V": [dicV1],
    "W": [dicW1],
    "X": [dicX1],
    "Y": [dicY1],
    "Z": [dicZ1],
  };

  static List<dynamic> defaultTypes = [
    {"Type": "Colors", "Trans": "TYPE_COLOR"},
    {"Type": "Directions", "Trans": "TYPE_DIRECTIONS"},
    {"Type": "Nationalities", "Trans": "TYPE_NATIONALITIES"},
    {"Type": "Number", "Trans": "TYPE_NUMBER"},
    {"Type": "Opposites", "Trans": "TYPE_OPPOSITES"},
    {"Type": "Part_Speech", "Trans": "TYPE_PART_SPEECH"},
    {"Type": "Themes", "Trans": "TYPE_THEMES"},
    {"Type": "Times", "Trans": "TYPE_TIMES"}
  ];
  static List<dynamic> dropdownTypes = defaultTypes;

  static dynamic defaultData = {
    "COMPLETED_TABLES": [
      {"Type": "Colors", "Table": "blue"},
      {"Type": "Colors", "Table": "brown"},
      {"Type": "Colors", "Table": "gray"},
      {"Type": "Colors", "Table": "green"},
      {"Type": "Colors", "Table": "orange"},
      {"Type": "Colors", "Table": "pink"},
      {"Type": "Colors", "Table": "purple"},
      {"Type": "Colors", "Table": "red"},
      {"Type": "Colors", "Table": "white"},
      {"Type": "Colors", "Table": "yellow"},
      {"Type": "Directions", "Table": "east"},
      {"Type": "Directions", "Table": "north"},
      {"Type": "Directions", "Table": "northwest"},
      {"Type": "Directions", "Table": "south"},
      {"Type": "Directions", "Table": "southeast"},
      {"Type": "Directions", "Table": "southwest"},
      {"Type": "Directions", "Table": "west"},
      {"Type": "Nationalities", "Table": "afghanistan"},
      {"Type": "Nationalities", "Table": "africa"},
      {"Type": "Nationalities", "Table": "asia"},
      {"Type": "Nationalities", "Table": "australia"},
      {"Type": "Nationalities", "Table": "belgium"},
      {"Type": "Nationalities", "Table": "canada"},
      {"Type": "Nationalities", "Table": "china"},
      {"Type": "Nationalities", "Table": "denmark"},
      {"Type": "Nationalities", "Table": "egypt"},
      {"Type": "Nationalities", "Table": "europe"},
      {"Type": "Nationalities", "Table": "finland"},
      {"Type": "Nationalities", "Table": "france"},
      {"Type": "Nationalities", "Table": "germany"},
      {"Type": "Nationalities", "Table": "greece"},
      {"Type": "Nationalities", "Table": "india"},
      {"Type": "Nationalities", "Table": "iraq"},
      {"Type": "Nationalities", "Table": "ireland"},
      {"Type": "Nationalities", "Table": "italy"},
      {"Type": "Nationalities", "Table": "japan"},
      {"Type": "Nationalities", "Table": "netherlandsdt"},
      {"Type": "Nationalities", "Table": "northamerica"},
      {"Type": "Nationalities", "Table": "norway"},
      {"Type": "Nationalities", "Table": "pakistan"},
      {"Type": "Nationalities", "Table": "portugal"},
      {"Type": "Nationalities", "Table": "rome"},
      {"Type": "Nationalities", "Table": "spain"},
      {"Type": "Nationalities", "Table": "sweden"},
      {"Type": "Nationalities", "Table": "uk"},
      {"Type": "Nationalities", "Table": "usa"},
      {"Type": "Nationalities", "Table": "vietnam"},
      {"Type": "Number", "Table": "eight"},
      {"Type": "Number", "Table": "five"},
      {"Type": "Number", "Table": "four"},
      {"Type": "Number", "Table": "nine"},
      {"Type": "Number", "Table": "one"},
      {"Type": "Number", "Table": "seven"},
      {"Type": "Number", "Table": "six"},
      {"Type": "Number", "Table": "ten"},
      {"Type": "Number", "Table": "three"},
      {"Type": "Number", "Table": "two"},
      {"Type": "Opposites", "Table": "above"},
      {"Type": "Opposites", "Table": "afraid"},
      {"Type": "Opposites", "Table": "alive"},
      {"Type": "Opposites", "Table": "bad"},
      {"Type": "Opposites", "Table": "behind"},
      {"Type": "Opposites", "Table": "below"},
      {"Type": "Opposites", "Table": "bent"},
      {"Type": "Opposites", "Table": "best"},
      {"Type": "Opposites", "Table": "big"},
      {"Type": "Opposites", "Table": "blurry"},
      {"Type": "Opposites", "Table": "bored"},
      {"Type": "Opposites", "Table": "brave"},
      {"Type": "Opposites", "Table": "bright"},
      {"Type": "Opposites", "Table": "buy"},
      {"Type": "Opposites", "Table": "chaos"},
      {"Type": "Opposites", "Table": "cheap"},
      {"Type": "Opposites", "Table": "clean"},
      {"Type": "Opposites", "Table": "clear"},
      {"Type": "Opposites", "Table": "closed"},
      {"Type": "Opposites", "Table": "cold"},
      {"Type": "Opposites", "Table": "complicated"},
      {"Type": "Opposites", "Table": "crazy"},
      {"Type": "Opposites", "Table": "cruel"},
      {"Type": "Opposites", "Table": "dark"},
      {"Type": "Opposites", "Table": "dead"},
      {"Type": "Opposites", "Table": "deep"},
      {"Type": "Opposites", "Table": "delicious"},
      {"Type": "Opposites", "Table": "different"},
      {"Type": "Opposites", "Table": "difficult"},
      {"Type": "Opposites", "Table": "dirty"},
      {"Type": "Opposites", "Table": "disgusting"},
      {"Type": "Opposites", "Table": "dry"},
      {"Type": "Opposites", "Table": "easy"},
      {"Type": "Opposites", "Table": "energetic"},
      {"Type": "Opposites", "Table": "excited"},
      {"Type": "Opposites", "Table": "expensive"},
      {"Type": "Opposites", "Table": "far"},
      {"Type": "Opposites", "Table": "fast"},
      {"Type": "Opposites", "Table": "fat"},
      {"Type": "Opposites", "Table": "female"},
      {"Type": "Opposites", "Table": "few"},
      {"Type": "Opposites", "Table": "fiction"},
      {"Type": "Opposites", "Table": "found"},
      {"Type": "Opposites", "Table": "fragrant"},
      {"Type": "Opposites", "Table": "go"},
      {"Type": "Opposites", "Table": "good"},
      {"Type": "Opposites", "Table": "hard"},
      {"Type": "Opposites", "Table": "heavy"},
      {"Type": "Opposites", "Table": "hot"},
      {"Type": "Opposites", "Table": "infrontof"},
      {"Type": "Opposites", "Table": "kind"},
      {"Type": "Opposites", "Table": "light"},
      {"Type": "Opposites", "Table": "loose"},
      {"Type": "Opposites", "Table": "lose"},
      {"Type": "Opposites", "Table": "lost"},
      {"Type": "Opposites", "Table": "loud"},
      {"Type": "Opposites", "Table": "male"},
      {"Type": "Opposites", "Table": "many"},
      {"Type": "Opposites", "Table": "narrow"},
      {"Type": "Opposites", "Table": "near"},
      {"Type": "Opposites", "Table": "normal"},
      {"Type": "Opposites", "Table": "old"},
      {"Type": "Opposites", "Table": "open"},
      {"Type": "Opposites", "Table": "organized"},
      {"Type": "Opposites", "Table": "poor"},
      {"Type": "Opposites", "Table": "pretty"},
      {"Type": "Opposites", "Table": "quiet"},
      {"Type": "Opposites", "Table": "recent"},
      {"Type": "Opposites", "Table": "rich"},
      {"Type": "Opposites", "Table": "rough"},
      {"Type": "Opposites", "Table": "same"},
      {"Type": "Opposites", "Table": "sane"},
      {"Type": "Opposites", "Table": "sell"},
      {"Type": "Opposites", "Table": "shallow"},
      {"Type": "Opposites", "Table": "short"},
      {"Type": "Opposites", "Table": "simple"},
      {"Type": "Opposites", "Table": "slow"},
      {"Type": "Opposites", "Table": "small"},
      {"Type": "Opposites", "Table": "smart"},
      {"Type": "Opposites", "Table": "smooth"},
      {"Type": "Opposites", "Table": "soft"},
      {"Type": "Opposites", "Table": "stinky"},
      {"Type": "Opposites", "Table": "stop"},
      {"Type": "Opposites", "Table": "straight"},
      {"Type": "Opposites", "Table": "strange"},
      {"Type": "Opposites", "Table": "strong"},
      {"Type": "Opposites", "Table": "tall"},
      {"Type": "Opposites", "Table": "thick"},
      {"Type": "Opposites", "Table": "thin"},
      {"Type": "Opposites", "Table": "tight"},
      {"Type": "Opposites", "Table": "tired"},
      {"Type": "Opposites", "Table": "truth"},
      {"Type": "Opposites", "Table": "ugly"},
      {"Type": "Opposites", "Table": "weak"},
      {"Type": "Opposites", "Table": "wet"},
      {"Type": "Opposites", "Table": "wide"},
      {"Type": "Opposites", "Table": "win"},
      {"Type": "Opposites", "Table": "worst"},
      {"Type": "Part_Speech", "Table": "adjective"},
      {"Type": "Part_Speech", "Table": "adjectiveage"},
      {"Type": "Part_Speech", "Table": "adjectivecolor"},
      {"Type": "Part_Speech", "Table": "adjectiveintensity"},
      {"Type": "Part_Speech", "Table": "adjectivematerial"},
      {"Type": "Part_Speech", "Table": "adjectivenationality"},
      {"Type": "Part_Speech", "Table": "adjectivenumber"},
      {"Type": "Part_Speech", "Table": "adjectivequality"},
      {"Type": "Part_Speech", "Table": "adjectivereligion"},
      {"Type": "Part_Speech", "Table": "adjectiveshape"},
      {"Type": "Part_Speech", "Table": "adjectivesize"},
      {"Type": "Part_Speech", "Table": "adjectivetexture"},
      {"Type": "Part_Speech", "Table": "adverb"},
      {"Type": "Part_Speech", "Table": "conjunction"},
      {"Type": "Part_Speech", "Table": "noun"},
      {"Type": "Part_Speech", "Table": "preposition"},
      {"Type": "Part_Speech", "Table": "verb"},
      {"Type": "Themes", "Table": "business"},
      {"Type": "Themes", "Table": "drama"},
      {"Type": "Themes", "Table": "entertainment"},
      {"Type": "Themes", "Table": "fashion"},
      {"Type": "Themes", "Table": "food"},
      {"Type": "Themes", "Table": "health"},
      {"Type": "Themes", "Table": "military"},
      {"Type": "Themes", "Table": "music"},
      {"Type": "Themes", "Table": "politics"},
      {"Type": "Themes", "Table": "religion"},
      {"Type": "Themes", "Table": "science"},
      {"Type": "Themes", "Table": "subject"},
      {"Type": "Themes", "Table": "technology"},
      {"Type": "Times", "Table": "after"},
      {"Type": "Times", "Table": "beginning"},
      {"Type": "Times", "Table": "early"},
      {"Type": "Times", "Table": "finish"},
      {"Type": "Times", "Table": "later"},
      {"Type": "Times", "Table": "now"},
      {"Type": "Times", "Table": "past"}
    ],
    "CATEGORIES": {
      "Colors": {
        "1": "Colors",
        "2": "Couleurs",
        "3": "Farben",
        "4": "Colori",
        "5": "Colores",
        "8": "Colors",
        "12": "Couleurs",
        "13": "Farben",
        "20": "Colori",
        "34": "Colores"
      },
      "Directions": {
        "1": "Directions",
        "2": "Directions",
        "3": "Richtungen",
        "4": "Indicazioni",
        "5": "Direcciones",
        "8": "Directions",
        "12": "Directions",
        "13": "Richtungen",
        "20": "Indicazioni",
        "34": "Direcciones"
      },
      "Materials": {
        "1": "Materials",
        "2": "Matériaux",
        "3": "Materialien",
        "4": "Materiali",
        "5": "Materiales",
        "8": "Materials",
        "12": "Matériaux",
        "13": "Materialien",
        "20": "Materiali",
        "34": "Materiales"
      },
      "Nationalities": {
        "1": "Nationalities",
        "2": "Nationalités",
        "3": "Nationalitäten",
        "4": "Nazionalità",
        "5": "Nacionalidades",
        "8": "Nationalities",
        "12": "Nationalités",
        "13": "Nationalitäten",
        "20": "Nazionalità",
        "34": "Nacionalidades"
      },
      "Number": {
        "1": "Number",
        "2": "Nombre",
        "3": "Nummer",
        "4": "Numero",
        "5": "Número",
        "8": "Number",
        "12": "Nombre",
        "13": "Nummer",
        "20": "Numero",
        "34": "Número"
      },
      "Opposites": {
        "1": "Opposites",
        "2": "Les contraires",
        "3": "Gegensätze",
        "4": "Gli opposti",
        "5": "Opuestos",
        "8": "Opposites",
        "12": "Les contraires",
        "13": "Gegensätze",
        "20": "Gli opposti",
        "34": "Opuestos"
      },
      "Part_Speech": {
        "1": "Part_Speech",
        "2": "Part_Speech",
        "3": "Teil_Rede",
        "4": "Parte_Discorso",
        "5": "Parte_discurso",
        "8": "Part_Speech",
        "12": "Part_Speech",
        "13": "Teil_Rede",
        "20": "Parte_Discorso",
        "34": "Parte_discurso"
      },
      "Religions": {
        "1": "Religions",
        "2": "Religions",
        "3": "Religionen",
        "4": "Religioni",
        "5": "Religiones",
        "8": "Religions",
        "12": "Religions",
        "13": "Religionen",
        "20": "Religioni",
        "34": "Religiones"
      },
      "Shapes": {
        "1": "Shapes",
        "2": "Formes",
        "3": "Formen",
        "4": "Forme",
        "5": "formas",
        "8": "Shapes",
        "12": "Formes",
        "13": "Formen",
        "20": "Forme",
        "34": "formas"
      },
      "Themes": {
        "1": "Themes",
        "2": "Thèmes",
        "3": "Themen",
        "4": "Temi",
        "5": "Temas",
        "8": "Themes",
        "12": "Thèmes",
        "13": "Themen",
        "20": "Temi",
        "34": "Temas"
      },
      "Times": {
        "1": "Times",
        "2": "Fois",
        "3": "Mal",
        "4": "Volte",
        "5": "Veces",
        "8": "Times",
        "12": "Fois",
        "13": "Mal",
        "20": "Volte",
        "34": "Veces"
      }
    }
  };
}
