# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :deploy do
    app_store_connect_api_key(
      key_id: "WC3F4SWD8K",
      issuer_id: "ed80abd4-c478-4030-9412-ef6d2e3011a1",
      key_filepath: File.expand_path("../../../lfq_fastlane_key.p8", __dir__)
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store(
      app_identifier: "com.lfq.acrostics-maker",
      precheck_include_in_app_purchases: false,
      skip_screenshots: true, 
      skip_metadata: false,
      submit_for_review:true,
      automatic_release:true,
      force:true      
    )
  end
end
